### ISSUE TITLE
SSR / Hydration HTML mismatch when rendering view! macro inline condition

### ISSUE THREAD

**Issue by danielnehrig** [framesurge/perseus#202]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> Perseus and Sycamore hydration html mismatch.
With inline `view!` macro conditional rendering.

The steps to reproduce this issue are as follows:
> Given following syntax Perseus is able to render the HTML.
But upon wasm / sycamore hydration is throwing a client side error.
```rust
view! {cx,
  div() {
    ({ if *state.get() { "Ok" } else { "nope" }})
  }
}
```

A minimum reproducible example is available at <I'll add this soon I promise>.
- Hydration-related: true
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWh5ZHJhdGlvbg==

</details>

**Comment by arctic-hen7** [comment]
I think this is a pure Sycamore bug, and should be reported there instead. @lukechu10 isn't this a known bug on your end?

**Comment by danielnehrig** [comment]
```
perseus = { version = "0.4.0-beta.10", features = [ "hydrate" ] }
sycamore = { version = "^0.8.2", features = ["ssr", "hydrate" ] }
```

**Comment by danielnehrig** [comment]
i guess i close this for now and reopen when it occurs again
