### ISSUE TITLE
Suspense fails

### ISSUE THREAD

**Issue by arctic-hen7** [framesurge/perseus#225]
### Discussed in https://github.com/framesurge/perseus/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **afidegnum** September 14, 2022</sup>
I have introduced the dynamic block using [transitions](https://github.com/afidegnum/sycatest/blob/master/src/main.rs)  into[ the component ](https://github.com/commune-org/linksapp/blob/main/src/components/index_hero.rs) and I'm facing the following perseus compilation error: 

```
warning: `linksapp` (bin "linksapp") generated 11 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 51.78s
     Running `dist/target_engine/debug/linksapp`
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/task/local.rs:316:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

What could be the cause?</div>

**Comment by arctic-hen7** [comment]
Investigating this further, Perseus is actually respecting Sycamore's scope boundaries perfectly, and the structure of the render core in Perseus makes it impossible to do anything else (we have to call those functions with a `Scope` anyway). The problem here seems to be, from a quick `RUST_BACKTRACE=1`, that Tokio doesn't like the fact that Perseus builds everything in parallel. It *seems* to be that that is somehow causing this error.

@lukechu10 can you shed any light on why this might be?

**Comment by arctic-hen7** [comment]
The most obvious temporary solution to this would be to create a Perseus wrapper for `Suspense` that just renders the loading state on the engine-side, since I'm willing to call that a `Suspense` should never be evaluated on the engine-side (the state platform replaces that).

**Comment by afidegnum** [comment]
ok, The issue is still not resolved from my end.

**Comment by arctic-hen7** [comment]
@afidegnum yes, I've just been postulating a fix. It's non-trivial to fix this at the moment, since Perseus' build system seems to render this impossible right now. I imagine there is a way to fix this, but I haven't gotten around to it yet. It should be done by the next release.
