### ISSUE TITLE
CLI fails in windows for users with spaces in their username

### ISSUE THREAD

**Issue by IsaacTay** [framesurge/perseus#227]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> Perseus build functions fail if you have a space in your username on windows.
Known to affect perseus build/export/serve
Since perseus defaults to using the cache directory in windows, the call to "powershell -command C:\Users\First Last\..." doesn't work due to the space.

The steps to reproduce this issue are as follows:
> Create a windows user with a space in the username.

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaSxhdXRob3Itd2lsbGluZy10by1pbXBs

</details>

**Comment by arctic-hen7** [comment]
Well that's a problem. What's the exact error message you're getting?

**Comment by IsaacTay** [comment]
```
 [1/2] 📦 Exporting your app's pages...
 [2/2] 🏗️  Building your app to Wasm...❌
C:\Users\Isaac : The term 'C:\Users\Isaac' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Users\Isaac Tay\AppData\Local\perseus\perseus_cli\cache\tools\wasm ...
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Isaac:String) [], CommandNotFoundException
  [1/2] 📦 Exporting your app's pages...✅
  [2/2] 🏗️  Building your app to Wasm...❌
```

It should be fixable by changing the tool path for windows from "C:\Users\..." to "& 'C:\Users\...' ", though I'm not sure if that's the best fix for this

**Comment by IsaacTay** [comment]
```
 ⠄ [1/2] 📦 Exporting your app's pages...
  [2/2] 🏗️  Building your app to Wasm...❌
C:\Users\Isaac : The term 'C:\Users\Isaac' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Users\Isaac Tay\AppData\Local\perseus\perseus_cli\cache\tools\wasm ...
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Isaac:String) [], CommandNotFoundException
  [1/2] 📦 Exporting your app's pages...✅
  [2/2] 🏗️  Building your app to Wasm...❌
```

It should be fixable by modifying the toolpath for window from "C:\Users\..." to "& 'C:\Users\...' ".
Sorry for closing the issue by accident
