### ISSUE TITLE
Static aliases fail to create directory structure

### ISSUE THREAD

**Issue by bluelhf** [framesurge/perseus#236]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> Static aliases do not attempt to create the directory tree of their target

The steps to reproduce this issue are as follows:
> Attempt to use a static alias with a target directory (to which the files will be copied by Perseus) that does not yet exist in dist/ — The target engine will panic at run-time instead of creating the directory structure automatically.

A minimum reproducible example is not available.
- Hydration-related: false
- The author is willing to attempt a fix: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxhdXRob3Itd2lsbGluZy10by1pbXBs

</details>

**Comment by arctic-hen7** [comment]
If I'm understanding you correctly, this is deliberate behavior, since the system needs to copy/symlink static aliases early on. The aliases must exist for this to work. 

Could you explain exactly what you're trying to do?

**Comment by bluelhf** [comment]
Ah, I am simply not braining at the moment — the problem was that I had failed to update the target for generating the files with `css_mod`, and nothing was wrong with Perseus at all. Closing as intended behaviour... I should really get some sleep.

**Comment by arctic-hen7** [comment]
Haha understood! I think we've all been somewhere like that!
