### ISSUE TITLE
perseus serve -w stuck on infinite loop when using build.rs build script. 

### ISSUE THREAD

**Issue by Mikephii** [framesurge/perseus#250]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> using perseus serve -w is failing to build for me. gets stuck in an infinite loop of steps 1, 2, 3, 1, 2, 3, .....

The steps to reproduce this issue are as follows:
> not sure, on apple M1 and implemented a custom build script that parses sass .scss files and injects css code into a styles.css  file in /static for use in the app. I think this build script modification to static/styles.css is triggering the watch update. 

A minimum reproducible example is available at <https://github.com/Mikephii/Perseus-with-sass>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaQ==

</details>

**Comment by arctic-hen7** [comment]
That's almost certainly because of where you're putting the output file. Try putting it in `dist/` instead and using a static alias, that should work.

(The CLI not being able to ignore watch paths is a known bug. You can add them, but not remove them. That will be fixed shortly, and, if that is the issue, then I might keep this issue open until that's done.)

**Comment by arctic-hen7** [comment]
Also, a plugin might work better for this if you'd like to hook directly into the Perseus build process. (It wouldn't solve this problem though.) Then you'd be able to neatly output failures, and contribute your work to the community (it sounds quite useful!) as a library.

**Comment by Mikephii** [comment]
thanks! will move to /dist for time being and look into building a plugin.

**Comment by arctic-hen7** [comment]
The next beta version of Perseus will let you exclude paths from watching by adding `--custom-watch !static/styles.css` in your case. I'll close this for, since that should make this sort of thing much easier.

**Comment by rieval** [comment]
> The next beta version of Perseus will let you exclude paths from watching by adding `--custom-watch !static/styles.css` in your case. I'll close this for, since that should make this sort of thing much easier.

Is it possible to configure this in `config.toml`? Maybe it could be a list of files.

**Comment by arctic-hen7** [comment]
In `Cargo.toml`, maybe! That's a very good idea actually, I'll put that in v0.4.1 I think.
