### ISSUE TITLE
Using global state in a Capsule as well as a Template leads to unreachable code being reached at build-time

### ISSUE THREAD

**Issue by Miroito** [framesurge/perseus#280]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> Using global state in a capsule and a template where this capsule is used panics at build-time

The steps to reproduce this issue are as follows:
> See MRE.

A minimum reproducible example is available at <https://github.com/Miroito/capsule-global-state>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWRlcGxveW1lbnQ=

</details>

**Comment by arctic-hen7** [comment]
This is actually very easy to fix: Perseus does the logical thing and internally caches any global state from the server the first time it's accessed, but that should not be happening on the server-side, which it is! This should be a trivial fix.

**Comment by arctic-hen7** [comment]
I'll release v0.4.1 with this fix ASAP.
