### ISSUE TITLE
Fail proceed 'perseus build' after upgraded to v0.4.1

### ISSUE THREAD

**Issue by mhfan** [framesurge/perseus#290]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> $ perseus build
  � Installing external tools...❌
Error: couldn't extract 'wasm-bindgen' (do you have the necessary permissions?)
Caused by:
        failed to iterate over archive
        Caused by:
                failed to fill whole buffer

The steps to reproduce this issue are as follows:
> $ perseus new foo
$ cd foo
$ perseus build

perseus-cli@0.4.0 works.

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaQ==

</details>

**Comment by mhfan** [comment]
I believe this patch will fix it.

https://github.com/framesurge/perseus/pull/291/commits/4bc54b8121a1686ac33083c26da1f1612c572d7d

**Comment by arctic-hen7** [comment]
Great, have you tried installing the CLI from there using a git dependency to make sure? If so, I'm happy to release v0.4.1 ASAP.

**Comment by mhfan** [comment]
Yes, I checked and it works now.

$ cargo install --git https://github.com/framesurge/perseus.git perseus-cli

$ perseus new foo
$ cd foo

$ perseus build
  � Generating Cargo lockfile...✅
  � Installing external tools...✅
  [1/2] � Generating your app...✅
  [2/2] �️  Building your app to Wasm...✅
